import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, useWindowDimensions, View } from 'react-native';
import { AppShell, Button, Card, SectionTitle } from '@/components/ui';
import { colors, radii } from '@/constants/theme';
import { history } from '@/data/mock';

export default function History() {
  const { width } = useWindowDimensions(); const wide = width > 760;
  return <AppShell title="Progress" subtitle="Track changes against your own walking baseline.">
    <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.scroll}>
      <Card style={styles.chartCard}><View style={styles.chartHeader}><View><Text style={styles.overline}>OVERALL GAIT SCORE</Text><View style={styles.scoreLine}><Text style={styles.score}>73</Text><View style={styles.up}><Ionicons name="arrow-up" size={12} color={colors.success} /><Text style={styles.upText}>6 points</Text></View></View></View><Text style={styles.range}>Last 30 days</Text></View><View style={styles.chart}><View style={styles.gridLine} /><View style={[styles.gridLine, { top: '50%' }]} /><View style={[styles.gridLine, { top: '100%' }]} /><View style={styles.chartColumns}>{[67, 70, 73].map((v, i) => <View key={v} style={styles.column}><View style={[styles.bar, { height: `${v}%` }]}><Text style={styles.barLabel}>{v}</Text></View><Text style={styles.date}>{history[2-i].date}</Text></View>)}</View></View></Card>
      <View style={[styles.grid, !wide && { flexDirection: 'column' }]}><View style={{ flex: 2 }}><SectionTitle>Assessment history</SectionTitle><Card style={{ padding: 5 }}>{history.map((h, i) => <Pressable key={h.date} onPress={() => router.push('/report/latest')} style={[styles.row, i < history.length - 1 && styles.border]}><View style={styles.dateBox}><Text style={styles.month}>{h.date.split(' ')[0].toUpperCase()}</Text><Text style={styles.day}>{h.date.split(' ')[1]}</Text></View><View style={{ flex: 1 }}><Text style={styles.rowTitle}>{h.note}</Text><Text style={styles.rowMeta}>Side view Â· 15 sec Â· Good video quality</Text></View><Text style={styles.rowScore}>{h.score}</Text><Ionicons name="chevron-forward" size={18} color="#AAB7B4" /></Pressable>)}</Card></View><View style={{ flex: 1 }}><SectionTitle>Consistency</SectionTitle><Card><View style={styles.consistencyIcon}><Ionicons name="calendar-outline" size={27} color={colors.primary} /></View><Text style={styles.consistencyTitle}>3 assessments</Text><Text style={styles.consistencyText}>Youâ€™re building a useful baseline. Retest every two weeks under similar conditions.</Text><Button label="Record next walk" onPress={() => router.push('/assess')} /></Card></View></View>
    </ScrollView>
  </AppShell>;
}

const styles = StyleSheet.create({
  scroll: { gap: 28 }, chartCard: { minHeight: 330 }, chartHeader: { flexDirection: 'row', justifyContent: 'space-between' }, overline: { color: colors.primary, fontSize: 10, fontWeight: '800', letterSpacing: 1.1 }, scoreLine: { flexDirection: 'row', alignItems: 'center', gap: 12, marginTop: 5 }, score: { color: colors.ink, fontSize: 40, fontWeight: '800' }, up: { backgroundColor: colors.mintLight, borderRadius: radii.pill, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 9, paddingVertical: 5 }, upText: { color: colors.success, fontSize: 10, fontWeight: '700' }, range: { color: colors.inkMuted, fontSize: 11 }, chart: { flex: 1, marginTop: 25, position: 'relative' }, gridLine: { position: 'absolute', left: 0, right: 0, top: 0, height: 1, backgroundColor: '#E7ECE9' }, chartColumns: { flex: 1, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-around' }, column: { width: '22%', height: '100%', justifyContent: 'flex-end', alignItems: 'center' }, bar: { width: '45%', backgroundColor: colors.primary, borderTopLeftRadius: 8, borderTopRightRadius: 8, alignItems: 'center' }, barLabel: { color: colors.white, fontSize: 10, fontWeight: '800', marginTop: 8 }, date: { color: colors.inkMuted, fontSize: 10, marginTop: 8 }, grid: { flexDirection: 'row', gap: 24 }, row: { minHeight: 83, flexDirection: 'row', alignItems: 'center', gap: 13, paddingHorizontal: 14 }, border: { borderBottomWidth: 1, borderBottomColor: '#EDF1EF' }, dateBox: { width: 46, height: 51, borderRadius: 12, backgroundColor: colors.mintLight, alignItems: 'center', justifyContent: 'center' }, month: { color: colors.primary, fontSize: 8, fontWeight: '800' }, day: { color: colors.ink, fontSize: 16, fontWeight: '800', marginTop: 2 }, rowTitle: { color: colors.ink, fontSize: 12, fontWeight: '700' }, rowMeta: { color: colors.inkMuted, fontSize: 9, marginTop: 5 }, rowScore: { color: colors.ink, fontSize: 22, fontWeight: '800' }, consistencyIcon: { width: 52, height: 52, borderRadius: 16, backgroundColor: colors.mint, alignItems: 'center', justifyContent: 'center' }, consistencyTitle: { color: colors.ink, fontSize: 20, fontWeight: '800', marginTop: 15 }, consistencyText: { color: colors.inkMuted, fontSize: 12, lineHeight: 19, marginVertical: 10 },
});
