import { Ionicons } from '@expo/vector-icons';
import { ScrollView, StyleSheet, Switch, Text, useWindowDimensions, View } from 'react-native';
import { AppShell, Button, Card, SectionTitle } from '@/components/ui';
import { colors } from '@/constants/theme';

const details = [['Age range', '20â€“29'], ['Height', '172 cm'], ['Walking aid', 'None'], ['Preferred units', 'Metric']];

export default function Profile() {
  const { width } = useWindowDimensions(); const wide = width > 780;
  return <AppShell title="Profile & settings" subtitle="Personalize assessments and manage your data.">
    <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.scroll}>
      <View style={[styles.grid, !wide && { flexDirection: 'column' }]}><View style={styles.side}><Card style={styles.identity}><View style={styles.avatar}><Text style={styles.initials}>MR</Text></View><Text style={styles.name}>Mahir Muntasir</Text><Text style={styles.email}>mahir@example.com</Text><View style={styles.member}><Ionicons name="checkmark-circle" size={15} color={colors.success} /><Text style={styles.memberText}>Baseline established</Text></View></Card><Card style={styles.privacy}><Ionicons name="shield-checkmark-outline" size={26} color={colors.primary} /><Text style={styles.privacyTitle}>Privacy controls</Text><Text style={styles.privacyText}>You control access to your videos and health reports.</Text><Button label="Manage my data" secondary /></Card></View>
      <View style={styles.main}><SectionTitle>Assessment profile</SectionTitle><Card>{details.map((d, i) => <View key={d[0]} style={[styles.detailRow, i < details.length - 1 && styles.border]}><Text style={styles.detailLabel}>{d[0]}</Text><View style={styles.detailValue}><Text style={styles.detailText}>{d[1]}</Text><Ionicons name="chevron-forward" size={17} color="#9CABAA" /></View></View>)}</Card><SectionTitle>Notifications</SectionTitle><Card><View style={[styles.toggleRow, styles.border]}><View style={styles.toggleIcon}><Ionicons name="notifications-outline" size={19} color={colors.primary} /></View><View style={{ flex: 1 }}><Text style={styles.toggleTitle}>Retest reminders</Text><Text style={styles.toggleText}>A reminder every two weeks</Text></View><Switch value trackColor={{ true: colors.primary }} /></View><View style={styles.toggleRow}><View style={styles.toggleIcon}><Ionicons name="trending-up-outline" size={19} color={colors.primary} /></View><View style={{ flex: 1 }}><Text style={styles.toggleTitle}>Progress summaries</Text><Text style={styles.toggleText}>Monthly movement overview</Text></View><Switch value={false} trackColor={{ true: colors.primary }} /></View></Card><SectionTitle>About</SectionTitle><Card><View style={[styles.detailRow, styles.border]}><Text style={styles.detailLabel}>App version</Text><Text style={styles.detailText}>0.1.0 prototype</Text></View><View style={styles.detailRow}><Text style={styles.detailLabel}>Medical disclaimer</Text><Ionicons name="chevron-forward" size={17} color="#9CABAA" /></View></Card></View></View>
    </ScrollView>
  </AppShell>;
}

const styles = StyleSheet.create({
  scroll: { paddingBottom: 30 }, grid: { flexDirection: 'row', gap: 25 }, side: { flex: 1, gap: 18, minWidth: 260 }, main: { flex: 2, gap: 3 }, identity: { alignItems: 'center', paddingVertical: 31 }, avatar: { width: 78, height: 78, borderRadius: 39, backgroundColor: colors.mint, alignItems: 'center', justifyContent: 'center' }, initials: { color: colors.primaryDark, fontSize: 25, fontWeight: '800' }, name: { color: colors.ink, fontSize: 19, fontWeight: '800', marginTop: 14 }, email: { color: colors.inkMuted, fontSize: 11, marginTop: 4 }, member: { flexDirection: 'row', gap: 6, alignItems: 'center', marginTop: 15, backgroundColor: colors.mintLight, paddingHorizontal: 10, paddingVertical: 7, borderRadius: 20 }, memberText: { color: colors.success, fontSize: 10, fontWeight: '700' }, privacy: { backgroundColor: '#F1FAF7' }, privacyTitle: { color: colors.ink, fontSize: 16, fontWeight: '800', marginTop: 12 }, privacyText: { color: colors.inkMuted, fontSize: 11, lineHeight: 17, marginVertical: 8 }, detailRow: { minHeight: 60, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, border: { borderBottomWidth: 1, borderBottomColor: '#EDF1EF' }, detailLabel: { color: colors.ink, fontSize: 12, fontWeight: '600' }, detailValue: { flexDirection: 'row', alignItems: 'center', gap: 10 }, detailText: { color: colors.inkMuted, fontSize: 11 }, toggleRow: { minHeight: 72, flexDirection: 'row', alignItems: 'center', gap: 12 }, toggleIcon: { width: 38, height: 38, borderRadius: 12, backgroundColor: colors.mintLight, alignItems: 'center', justifyContent: 'center' }, toggleTitle: { color: colors.ink, fontSize: 12, fontWeight: '700' }, toggleText: { color: colors.inkMuted, fontSize: 10, marginTop: 4 },
});
