"""Generate portable exact-version constraints from the successfully tested virtual environment."""
import importlib.metadata
from pathlib import Path

packages = sorted((dist.metadata["Name"], dist.version) for dist in importlib.metadata.distributions()
                  if dist.metadata["Name"].lower() not in ("gaitsense-backend", "pip", "setuptools"))
target = Path(__file__).resolve().parents[1] / "constraints.txt"
target.write_text("# Generated by scripts/lock.py after verification on Python 3.12 / Windows.\n"
                  "# Re-test when changing these pins. Optional dependencies are installed only through extras.\n"
                  + "".join(f"{name}=={version}\n" for name, version in packages), encoding="utf-8")
print(f"Locked {len(packages)} tested dependency versions")
