import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, useWindowDimensions, View } from 'react-native';
import { AppShell, Button, Card, ScoreRing, SectionTitle } from '@/components/ui';
import { colors, radii } from '@/constants/theme';
import { recommendations, scoreBreakdown } from '@/data/mock';

export default function Report() {
  const { width } = useWindowDimensions();
  const wide = width >= 1000;
  return <AppShell title="Assessment report" subtitle="Recorded Aug 9, 2026 Â· Side view Â· 15 seconds" action={<Pressable style={styles.close} onPress={() => router.back()}><Ionicons name="close" size={22} color={colors.ink} /></Pressable>}>
    <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.scroll}>
      <Card style={styles.summary}><View style={styles.ring}><ScoreRing score={73} size={168} /></View><View style={styles.summaryCopy}><View style={styles.status}><Ionicons name="checkmark-circle" size={16} color={colors.success} /><Text style={styles.statusText}>STABLE GAIT PATTERN</Text></View><Text style={styles.title}>A solid result with room to improve posture.</Text><Text style={styles.body}>Your balance, walking pace, and left-right rhythm look consistent. We noticed a slight forward lean and reduced left arm swing.</Text><View style={styles.tags}><View style={styles.goodTag}><Text style={styles.goodText}>Fall risk: Low</Text></View><View style={styles.neutralTag}><Text style={styles.neutralText}>Confidence: 88%</Text></View></View></View></Card>
      <View style={[styles.grid, !wide && { flexDirection: 'column' }]}>
        <View style={styles.main}>
          <SectionTitle>Your breakdown</SectionTitle><Card>{scoreBreakdown.map((m, i) => <View key={m.label} style={[styles.metric, i === scoreBreakdown.length - 1 && { borderBottomWidth: 0 }]}><View style={[styles.metricIcon, { backgroundColor: `${m.color}18` }]}><Ionicons name={i === 0 ? 'body-outline' : i === 1 ? 'git-compare-outline' : i === 2 ? 'fitness-outline' : i === 3 ? 'speedometer-outline' : 'scale-outline'} size={19} color={m.color} /></View><View style={{ flex: 1 }}><View style={styles.metricHead}><Text style={styles.metricLabel}>{m.label}</Text><Text style={styles.metricScore}>{m.score}<Text style={styles.unit}>/100</Text></Text></View><View style={styles.track}><View style={[styles.fill, { width: `${m.score}%`, backgroundColor: m.color }]} /></View></View></View>)}</Card>
          <SectionTitle>What we noticed</SectionTitle><Card>{[
            ['alert-circle-outline', 'Mild stride asymmetry', 'Your left step was slightly shorter than your right step.', colors.amber],
            ['body-outline', 'Slight forward trunk lean', 'Your upper body leaned forward beyond the healthy reference range.', colors.coral],
            ['hand-left-outline', 'Reduced left arm swing', 'Your left arm moved through a smaller range than your right.', colors.blue],
          ].map((x, i) => <View key={x[1]} style={[styles.issue, i < 2 && styles.issueBorder]}><Ionicons name={x[0] as never} size={21} color={x[3]} /><View style={{ flex: 1 }}><Text style={styles.issueTitle}>{x[1]}</Text><Text style={styles.issueText}>{x[2]}</Text></View></View>)}</Card>
        </View>
        <View style={styles.side}><SectionTitle>Your next steps</SectionTitle><Card>{recommendations.map((r, i) => <View key={r.title} style={[styles.rec, i < recommendations.length - 1 && styles.issueBorder]}><View style={[styles.recIcon, { backgroundColor: r.tone }]}><Text style={styles.recNumber}>{i + 1}</Text></View><View style={{ flex: 1 }}><Text style={styles.issueTitle}>{r.title}</Text><Text style={styles.issueText}>{r.detail}</Text></View></View>)}<Button label="Set 2-week reminder" icon="notifications-outline" /></Card><Card style={styles.note}><Ionicons name="information-circle-outline" size={20} color={colors.primary} /><Text style={styles.noteText}>Scores are movement-screening estimates, not a medical diagnosis. Discuss new pain, falls, or neurological symptoms with a qualified clinician.</Text></Card></View>
      </View>
    </ScrollView>
  </AppShell>;
}

const styles = StyleSheet.create({
  scroll: { gap: 27 }, close: { width: 40, height: 40, borderRadius: 20, backgroundColor: colors.cream, alignItems: 'center', justifyContent: 'center' }, summary: { minHeight: 245, flexDirection: 'row', alignItems: 'center', padding: 32 }, ring: { marginHorizontal: 20 }, summaryCopy: { flex: 1, maxWidth: 660, paddingLeft: 20 }, status: { flexDirection: 'row', gap: 7, alignItems: 'center' }, statusText: { color: colors.success, fontSize: 10, fontWeight: '800', letterSpacing: 1.1 }, title: { color: colors.ink, fontSize: 27, lineHeight: 34, fontWeight: '800', marginTop: 12, letterSpacing: -.6 }, body: { color: colors.inkMuted, fontSize: 13, lineHeight: 21, marginTop: 10 }, tags: { flexDirection: 'row', gap: 8, marginTop: 16 }, goodTag: { backgroundColor: colors.mint, paddingHorizontal: 11, paddingVertical: 7, borderRadius: radii.pill }, goodText: { color: colors.primaryDark, fontSize: 10, fontWeight: '800' }, neutralTag: { backgroundColor: colors.cream, paddingHorizontal: 11, paddingVertical: 7, borderRadius: radii.pill }, neutralText: { color: colors.inkMuted, fontSize: 10, fontWeight: '700' }, grid: { flexDirection: 'row', gap: 26 }, main: { flex: 1.6, gap: 3 }, side: { flex: 1, gap: 3, minWidth: 290 }, metric: { flexDirection: 'row', gap: 13, alignItems: 'center', paddingVertical: 13, borderBottomWidth: 1, borderBottomColor: '#EDF1EF' }, metricIcon: { width: 40, height: 40, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, metricHead: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 }, metricLabel: { color: colors.ink, fontSize: 12, fontWeight: '700' }, metricScore: { color: colors.ink, fontSize: 13, fontWeight: '800' }, unit: { fontSize: 9, color: colors.inkMuted }, track: { height: 6, backgroundColor: '#EDF1EF', borderRadius: 4, overflow: 'hidden' }, fill: { height: '100%', borderRadius: 4 }, issue: { flexDirection: 'row', gap: 13, paddingVertical: 14 }, issueBorder: { borderBottomWidth: 1, borderBottomColor: '#EDF1EF' }, issueTitle: { color: colors.ink, fontSize: 12, fontWeight: '700' }, issueText: { color: colors.inkMuted, fontSize: 10, lineHeight: 16, marginTop: 4 }, rec: { flexDirection: 'row', gap: 12, paddingVertical: 15 }, recIcon: { width: 34, height: 34, borderRadius: 11, alignItems: 'center', justifyContent: 'center' }, recNumber: { color: colors.primaryDark, fontWeight: '800', fontSize: 11 }, note: { marginTop: 16, flexDirection: 'row', gap: 11, backgroundColor: colors.mintLight, padding: 16 }, noteText: { flex: 1, color: colors.inkMuted, fontSize: 10, lineHeight: 16 },
});
