const { withAndroidManifest, withDangerousMod, withGradleProperties } = require('expo/config-plugins');
const { mkdirSync, existsSync, readFileSync, writeFileSync } = require('node:fs');
const { join } = require('node:path');
module.exports = config => {
  config = withGradleProperties(config, config => {
    const item = config.modResults.find(p=>p.type==='property' && p.key==='android.minSdkVersion');
    if (item) item.value=String(Math.max(26,Number(item.value)||26));
    else config.modResults.push({type:'property',key:'android.minSdkVersion',value:'26'});
    // Bounded release-lint resource budget; preserve heap and other JVM flags.
    const jvm = config.modResults.find(p=>p.type==='property' && p.key==='org.gradle.jvmargs');
    const flags = (jvm?.value || '-Xmx2048m').replace(/(?:^|\s)-XX:MaxMetaspaceSize=\S+/g, '').trim();
    const value = `${flags} -XX:MaxMetaspaceSize=1024m`;
    if (jvm) jvm.value = value;
    else config.modResults.push({type:'property',key:'org.gradle.jvmargs',value});
    return config;
  });
  config = withAndroidManifest(config, config => {
  const manifest = config.modResults.manifest;
  manifest.$['xmlns:tools'] = 'http://schemas.android.com/tools';
  const app = manifest.application[0];
  app.$['android:allowBackup'] = 'false';
  app.$['tools:replace'] = [...new Set((app.$['tools:replace'] || '').split(',').filter(Boolean).concat('android:allowBackup'))].join(',');
  return config;
  });
  return withDangerousMod(config, ['android', async config => {
    // Auth-capable release permits INTERNET; gait capture/storage remain local.
    const directory = join(config.modRequest.platformProjectRoot, 'app/src/release');
    const file = join(directory, 'AndroidManifest.xml');
    const xml = '<!-- Generated by GaitSense offline privacy plugin -->\n<manifest xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools"><uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" tools:node="remove"/></manifest>\n';
    if (existsSync(file) && !readFileSync(file,'utf8').startsWith('<!-- Generated by GaitSense offline privacy plugin -->')) throw new Error('Existing release manifest needs manual privacy merge; refusing to overwrite.');
    mkdirSync(directory,{recursive:true}); writeFileSync(file,xml);
    return config;
  }]);
};
